sudo: required

language: python
python: 2.7

services:
  - docker

env:
  matrix:
    - TOX_ENV=py27
    - COMPOSE=True
  global:
    - secure: "PgEA6vDYZWAIZ3KyUTeA9SNSNR+eJU3kBkoEIsTnmnkyta0Z0VbIv98B9ApYeiC0VHpVzY1gblimmkXSY5+4oD9tUxpA630cUhE9iLNuo5o3MpRFun8nf8H6Jz2Y/PaPw3VPLKsH49LJYgJXeqgzoV7FHrpUP9Q3/5dycWybV2I="

git:
  submodules: false

before_install:
  - export GALAXY_HOME=/home/galaxy
  - export GALAXY_USER=admin@galaxy.org
  - export GALAXY_USER_EMAIL=admin@galaxy.org
  - export GALAXY_USER_PASSWD=admin
  - export BIOBLEND_GALAXY_API_KEY=admin
  - export BIOBLEND_GALAXY_URL=http://localhost:8080

  - sudo apt-get update -qq
  - sudo apt-get install docker-engine --no-install-recommends -y -o Dpkg::Options::="--force-confmiss" -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confnew"
  # xvfb is needed for selenium
  - sudo apt-get install xvfb sshpass --no-install-recommends -y
  # selenium headless mode
  - pip install pyvirtualdisplay selenium requests pyyaml
  - wget https://github.com/mozilla/geckodriver/releases/download/v0.16.0/geckodriver-v0.16.0-linux64.tar.gz
  - tar -xzf geckodriver-v0.16.0-linux64.tar.gz && sudo mv geckodriver /usr/bin/geckodriver && sudo chmod a+x /usr/bin/geckodriver

  - docker --version
  - docker info

  - git submodule update --init --recursive
  - sudo chown 1450 /tmp && sudo chmod a=rwx /tmp
  - |
    if [ "${COMPOSE}" ]
    then
        pip install docker-compose
        export WORKING_DIR="$TRAVIS_BUILD_DIR/compose"
        export DOCKER_RUN_CONTAINER="galaxy-web"
        INSTALL_REPO_ARG="--galaxy-url http://localhost:80"
        SAMPLE_TOOLS=/export/config/sample_tool_list.yaml
        cd "$WORKING_DIR"
        ./buildlocal.sh
        export COMPOSE_PROJECT_NAME=galaxy_compose
        docker-compose up -d
        sleep 120
        docker-compose logs
        # Define start functions
        docker_exec() {
          cd $WORKING_DIR
          docker-compose exec galaxy-web "$@"
        }
        docker_exec_run() {
          cd $WORKING_DIR
          docker-compose exec galaxy-web "$@"
        }
        docker_run() {
          cd $WORKING_DIR
          docker-compose run "$@"
        }
    else
        export WORKING_DIR="$TRAVIS_BUILD_DIR"
        export DOCKER_RUN_CONTAINER="quay.io/bgruening/galaxy"
        INSTALL_REPO_ARG=""
        SAMPLE_TOOLS=$GALAXY_HOME/ephemeris/sample_tool_list.yaml
        cd "$WORKING_DIR"
        docker build -t quay.io/bgruening/galaxy galaxy/
        mkdir local_folder
        docker run -d -p 8080:80 -p 8021:21 -p 8022:22 \
            --name galaxy \
            --privileged=true \
            -v `pwd`/local_folder:/export/ \
            -e GALAXY_CONFIG_ALLOW_USER_DATASET_PURGE=True \
            -e GALAXY_CONFIG_ALLOW_LIBRARY_PATH_PASTE=True \
            -e GALAXY_CONFIG_ENABLE_USER_DELETION=True \
            -e GALAXY_CONFIG_ENABLE_BETA_WORKFLOW_MODULES=True \
            -v /tmp/:/tmp/ \
            quay.io/bgruening/galaxy
        sleep 30
        docker logs galaxy
        # Define start functions
        docker_exec() {
          cd $WORKING_DIR
          docker exec -t -i galaxy "$@"
        }
        docker_exec_run() {
          cd $WORKING_DIR
          docker run quay.io/bgruening/galaxy "$@"
        }
        docker_run() {
          cd $WORKING_DIR
          docker run "$@"
        }

    fi
  - docker ps

script:
  # Test submitting jobs to an external slurm cluster
  - |
      if ! [ "${COMPOSE}" ]
      then
        # For compose slurm is already included and thus tested
        cd $TRAVIS_BUILD_DIR/test/slurm/ && bash test.sh && cd $WORKING_DIR
      fi
  # Test submitting jobs to an external gridengine cluster
  - |
      if ! [ "${COMPOSE}" ]
      then
        # This test is not testing compose, thus disabled
        cd $TRAVIS_BUILD_DIR/test/gridengine/ && bash test.sh && cd $WORKING_DIR
      fi
  # Test Web api
  - curl -v --fail $BIOBLEND_GALAXY_URL/api/version

  # Test FTP Server upload
  - date > time.txt && curl -v --fail -T time.txt ftp://localhost:8021 --user $GALAXY_USER:$GALAXY_USER_PASSWD
  # Test FTP Server get
  - curl -v --fail ftp://localhost:8021 --user $GALAXY_USER:$GALAXY_USER_PASSWD

  # Test SFTP Server
  - sshpass -p $GALAXY_USER_PASSWD sftp -v -P 8022 -o User=$GALAXY_USER -o "StrictHostKeyChecking no" localhost <<< $'put time.txt'
  # Test self-signed HTTPS
  - |
     docker_run -d --name httpstest -p 443:443 -e "USE_HTTPS=True" $DOCKER_RUN_CONTAINER
     sleep 60s && curl -v -k --fail https://127.0.0.1:443/api/version
     echo | openssl s_client -connect 127.0.0.1:443 2>/dev/null | openssl x509 -issuer -noout| grep selfsigned
     docker logs httpstest && docker stop httpstest && docker rm httpstest

  - cd $TRAVIS_BUILD_DIR/test/bioblend/ && . ./test.sh && cd $WORKING_DIR/

  # Test the 'old' tool installation script
  - docker_exec_run bash -c "install-repository $INSTALL_REPO_ARG '--url https://toolshed.g2.bx.psu.edu -o iuc --name bedtools --panel-section-name BEDTools'"
  - |
    if [ "$COMPOSE" ]
    then
      # Test without install-repository wrapper
      docker_exec_run bash -c 'cd $GALAXY_ROOT && python ./scripts/api/install_tool_shed_repositories.py --api admin -l http://localhost:80 --tool-deps --repository-deps --url https://toolshed.g2.bx.psu.edu -o iuc --name bedtools --panel-section-name BEDTools'
    fi
  # Test the 'new' tool installation script
  #  - docker_exec bash -c "install-tools $GALAXY_HOME/ephemeris/sample_tool_list.yaml"
  - |
    if [ "$COMPOSE" ]
    then
      # Compose uses the online installer (uses the running instance)
      docker_exec_run shed-install -g "http://localhost:80" -a admin -t "$SAMPLE_TOOLS"
    else
      docker_exec_run install-tools "$SAMPLE_TOOLS"
    fi
  # Test the Conda installation
  - docker_exec_run bash -c 'export PATH=$GALAXY_CONFIG_TOOL_DEPENDENCY_DIR/_conda/bin/:$PATH && conda --version && conda install samtools -c bioconda --yes'
  # Test Docker in Docker, used by Interactive Environments; This needs to be at the end as Docker takes some time to start.
  - docker_exec docker info

  # Selenium UI tests
  - docker run -d -p 4444:4444 -v /dev/shm:/dev/shm selenium/standalone-firefox
  - sleep 30s
  - mkdir ./selenium_galaxy/
  - wget -q -O - https://github.com/galaxyproject/galaxy/archive/release_17.01.tar.gz | tar xzf - --strip-components=1 -C ./selenium_galaxy/
  - wget https://raw.githubusercontent.com/galaxyproject/galaxy/dev/config/plugins/tours/core.galaxy_ui.yaml
  - ./selenium_galaxy/scripts/dump_tour.py -o selenium_img --selenium-headless --selenium-browser FIREFOX --galaxy_url http://localhost:8080 core.galaxy_ui.yaml
  - ls -l selenium_img

  # Check if the database image matches the current galaxy version
  - |
      if [ "${COMPOSE}" ]
      then
        cd $WORKING_DIR && bash ./dumpsql.sh
        git diff --exit-code $WORKING_DIR/galaxy-postgres/init-galaxy-db.sql.in || ( echo "Database dump does not equal dump in repository" && false )
      fi


after_success:
  - |
    if [ "$TRAVIS_PULL_REQUEST" == "false" -a "$TRAVIS_BRANCH" == "master" ]
    then
      echo "Generate and deploy html documentation"
      ./docs/bin/deploy_docs
    fi


notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/559f5480ac7a4ef238af
    on_success: change
    on_failure: always
    on_start: never
