kind: PersistentVolume
apiVersion: v1
metadata:
  name: pv-volume-rabbitmq
  labels:
    type: local
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/export/rabbitmq"
