galaxy_uwsgi:
  socket: :5555
  buffer-size: 16384
  processes: 1
  threads: 4
  offload-threads: 2
  static-map: /static/style=static/style/blue
  static-map: /static=static
  static-map: /favicon.ico=static/favicon.ico
  master: false
  virtualenv: .venv
  pythonpath: lib
  thunder-lock: false
  die-on-term: true
  hook-master-start: unix_signal:2 gracefully_kill_them_all
  hook-master-start: unix_signal:15 gracefully_kill_them_all
  py-call-osafterfork: true
  enable-threads: true

galaxy:
  tool_dependency_dir: /tool_deps
  tool_data_table_config_path: /cvmfs/data.galaxyproject.org/byhand/location/tool_data_table_conf.xml,/cvmfs/data.galaxyproject.org/managed/location/tool_data_table_conf.xml

# Probably needs more polishing, but at least it works..
slurm:
  ControlMachine: "slurmctld"
  AuthType: "auth/munge"
  CacheGroups: "0"
  CryptoType: "crypto/munge"
  MpiDefault: "none"
  ProctrackType: "proctrack/pgid"
  ReturnToService: "1"
  SlurmctldPidFile: "/var/run/slurmctld.pid"
  SlurmctldPort: "6817"
  SlurmdPidFile: "/var/run/slurmd.pid"
  SlurmdPort: "6818"
  SlurmdSpoolDir: "/tmp/slurmd"
  SlurmUser: "slurm"
  StateSaveLocation: "/tmp/slurm"
  SwitchType: "switch/none"
  TaskPlugin: "task/none"
  InactiveLimit: "0"
  KillWait: "30"
  MinJobAge: "300"
  SlurmctldTimeout: "120"
  SlurmdTimeout: "300"
  Waittime: "0"
  FastSchedule: "1"
  SchedulerType: "sched/backfill"
  SchedulerPort: "7321"
  SelectType: "select/cons_res"
  SelectTypeParameters: "CR_Core_Memory"
  AccountingStorageType: "accounting_storage/none"
  AccountingStoreJobComment: "YES"
  ClusterName: "Cluster"
  JobCompType: "jobcomp/none"
  JobAcctGatherFrequency: "30"
  JobAcctGatherType: "jobacct_gather/none"
  SlurmctldDebug: info
  SlurmdDebug: info
