version: "3"
services:
  galaxy-configurator:
    environment:
      - GALAXY_JOB_RUNNER=pulsar_rest
      - PULSAR_OVERWRITE_CONFIG=true
      - PULSAR_JOB_RUNNER=local
      - PULSAR_CONFIG_PRIVATE_TOKEN=changemeinproduction
      - GALAXY_PULSAR_URL=http://pulsar:8913
    volumes:
      - ${EXPORT_DIR:-./export}/pulsar/config:/pulsar/config
  pulsar:
    image: ${IMAGE_DOMAIN:-andreassko}/pulsar:${IMAGE_TAG:-latest}
    build: pulsar
    hostname: pulsar
    volumes:
      - ${EXPORT_DIR:-./export}/pulsar/config:/pulsar/config
      - ${EXPORT_DIR:-./export}/pulsar/dependencies:/pulsar/dependencies
    networks:
      - galaxy
