version: '2.1'
services:
  # proftpd container
  galaxy-proftpd:
    # build: galaxy-proftpd
    image: quay.io/galaxy/proftpd:compose
    environment:
        - proftpd_db_connection=galaxy@galaxy-postgres
        - proftpd_db_username=galaxy
        - proftpd_db_password=chaopagoosaequuashie
        - proftpd_files_dir=${EXPORT_DIR:-/export/}ftp
        - proftpd_use_sftp=True
        - proftpd_generate_ssh_key=False
        - proftpd_passive_port_low=30000
        - proftpd_passive_port_high=30010
    container_name: galaxy-proftpd
    hostname: galaxy-proftpd
    volumes_from:
        - galaxy-web
    expose:
        - 21
        - 22
    ports:
        - "8021:21"
        - "8022:22"
        - "30000-30010:30000-30010"
    restart: always

  galaxy-postgres:
    # If you are using the official postgres image, it needs to be populated by calling
    # docker-compose run galaxy install_db.sh
    # on first run
    # image: postgres
    # build: galaxy-postgres
    image: quay.io/galaxy/postgres:compose
    container_name: galaxy-postgres
    hostname: galaxy-postgres
    environment:
        - POSTGRES_PASSWORD=chaopagoosaequuashie
        - POSTGRES_USER=galaxy
        - POSTGRES_DB=galaxy
    volumes:
        - ./postgres-storage:/var/lib/postgresql/data

  # PostgreSQL admin suite
  pgadmin4:
    image: thajeztah/pgadmin4
    container_name: pgadmin4
    ports:
        - "5050:5050"
    links:
        - postgres
    # ToDO, not sure why this is failing
    #volumes:
        #- ./pgadmin:/pgadmin
    restart: unless-stopped

  # SLURM container - this is your compute cluster :)
  galaxy-slurm:
    # build: galaxy-slurm
    image: quay.io/galaxy/slurm:compose
    environment: {}
    container_name: galaxy-slurm
    hostname: galaxy-slurm
    volumes_from:
        - galaxy-web
    restart: always

  # This container initializes the galaxy export.
  galaxy-init:
    # build: galaxy-init
    image: quay.io/bgruening/galaxy-init:compose
    container_name: galaxy-init
    hostname: galaxy-init
    volumes:
        # This is the directory where all your files from Galaxy will be stored
        # on your host system. By default this is 'export' in your current working dir
        - ${EXPORT_DIR:-/export}/:/export/

  galaxy-htcondor:
    image: quay.io/bgruening/galaxy-htcondor:compose
    container_name: galaxy-htcondor
    hostname: galaxy-htcondor
    volumes_from:
        - galaxy-web

  galaxy-htcondor-executor:
    image: quay.io/bgruening/galaxy-htcondor-executor:compose
    container_name: galaxy-htcondor-executor
    hostname: galaxy-htcondor-executor
    # privileged is needed to run Docker jobs, moreover HTCondor wants
    # a RW cgroups mount. A RO cgroups mount throws an error in ProcD for running jobs.
    privileged: True
    environment:
        - CONDOR_HOST=galaxy-htcondor
    volumes_from:
        - galaxy-web
    volumes:
        - /var/run/docker.sock:/var/run/docker.sock

  # Message queue for better performance
  rabbitmq:
    image: rabbitmq:alpine
    container_name: galaxy-rabbitmq
    hostname: rabbitmq
    environment:
        - RABBITMQ_DEFAULT_USER=galaxy
        - RABBITMQ_DEFAULT_PASS=vaiJa3ieghai2ief0jao
        - RABBITMQ_DEFAULT_VHOST=galaxy
    volumes:
        - ${EXPORT_DIR:-/export}/rabbitmq:/var/lib/rabbitmq

  # This container provides the galaxy uwsgi webhandlers, job handlers, nginx
  galaxy-web:
    # build: galaxy-web
    image: quay.io/bgruening/galaxy-web:compose
    environment:
        # In case the galaxy-init container is not used, you need to include "sleeplock" to NONUSE
        - NONUSE=proftpd,postgres,slurmd,slurmctld
        - GALAXY_DEFAULT_ADMIN_USER=admin@galaxy.org
        - GALAXY_DEFAULT_ADMIN_PASSWORD=admin
        - GALAXY_DEFAULT_ADMIN_KEY=admin
        - GALAXY_HANDLER_NUMPROCS=2
        - UWSGI_PROCESSES=4
        - GALAXY_CONFIG_ALLOW_USER_DATASET_PURGE=True
        - GALAXY_CONFIG_ALLOW_LIBRARY_PATH_PASTE=True
        - GALAXY_CONFIG_ENABLE_USER_DELETION=True
        - GALAXY_CONFIG_ENABLE_BETA_WORKFLOW_MODULES=True
        - GALAXY_CONFIG_DATABASE_CONNECTION=postgresql://galaxy:chaopagoosaequuashie@galaxy-postgres/galaxy?client_encoding=utf8
        # Configurate admin and master api key. Can be overridden in galaxy.ini
        - GALAXY_CONFIG_ADMIN_USERS=admin@galaxy.org
        - GALAXY_CONFIG_MASTER_API_KEY=HSNiugRFvgT574F43jZ7N9F3
        - GALAXY_CONFIG_AMQP_INTERNAL_CONNECTION=amqp://galaxy:vaiJa3ieghai2ief0jao@rabbitmq/galaxy 
        # Condor
        - GALAXY_DESTINATIONS_DEFAULT=${GALAXY_DESTINATIONS_DEFAULT:-condor_cluster}
        - ENABLE_CONDOR=true
        - CONDOR_HOST=galaxy-htcondor
        - GALAXY_CONDOR_UNIVERSE=vanilla
        - GALAXY_DOCKER_ENABLED=${GALAXY_DOCKER_ENABLED:-false}
        - GALAXY_CONFIG_CLEANUP_JOB=${GALAXY_CONFIG_CLEANUP_JOB:-onsuccess}
    container_name: galaxy-web
    hostname: galaxy
    privileged: True
    ports:
        - "${GALAXY_PORT:-8080}:80" # nginx
    volumes:
        # This is the directory where all your files from Galaxy will be stored
        # on your host system
        - ${EXPORT_DIR:-/export}/:/export/
        - /var/run/docker.sock:/var/run/docker.sock

