name: CI
on: [push]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Cleanup to only use compose-v2 for now
      run: rm -R compose docs galaxy  test
    - name: Run shellcheck with reviewdog
      uses: reviewdog/action-shellcheck@v1.1.3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        reporter: github-check
        level: warning
        pattern: "*.sh"
    - name: Run hadolint with reviewdog
      uses: reviewdog/action-hadolint@v1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        reporter: github-check
  build_galaxy-server:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Set image tag
        id: image_tag
        run: echo "::set-output name=image_tag::${GITHUB_REF#refs/heads/}"
      - name: Build, Tag and Publish
        uses: whoan/docker-build-with-cache-action@v2
        with:
          username: ${{ secrets.dockerhub_username }}
          password: ${{ secrets.dockerhub_password }}
          image_name: andreassko/galaxy-server
          image_tag: ${{ steps.image_tag.outputs.image_tag }}
          context: ./compose-v2/galaxy-server
  build_galaxy-postgres:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Build, Tag and Publish
        uses: elgohr/Publish-Docker-Github-Action@master
        continue-on-error: false
        with:
          name: andreassko/galaxy-postgres
          username: ${{ secrets.dockerhub_username }}
          password: ${{ secrets.dockerhub_password }}
          workdir: ./compose-v2/galaxy-postgres
          cache: true
  build_galaxy-htcondor:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Build, Tag and Publish
        uses: elgohr/Publish-Docker-Github-Action@master
        continue-on-error: false
        with:
          name: andreassko/galaxy-htcondor
          username: ${{ secrets.dockerhub_username }}
          password: ${{ secrets.dockerhub_password }}
          workdir: ./compose-v2/galaxy-htcondor
          cache: true
  build_galaxy-configurator:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Build, Tag and Publish
        uses: elgohr/Publish-Docker-Github-Action@master
        continue-on-error: false
        with:
          name: andreassko/galaxy-configurator
          username: ${{ secrets.dockerhub_username }}
          password: ${{ secrets.dockerhub_password }}
          workdir: ./compose-v2/galaxy-configurator
          cache: true
  build_galaxy-bioblend-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Build, Tag and Publish
        uses: elgohr/Publish-Docker-Github-Action@master
        continue-on-error: false
        with:
          name: andreassko/galaxy-bioblend-test
          username: ${{ secrets.dockerhub_username }}
          password: ${{ secrets.dockerhub_password }}
          workdir: ./compose-v2/galaxy-bioblend-test
          cache: true
  build_galaxy-workflow-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Build, Tag and Publish
        uses: elgohr/Publish-Docker-Github-Action@master
        continue-on-error: false
        with:
          name: andreassko/galaxy-workflow-test
          username: ${{ secrets.dockerhub_username }}
          password: ${{ secrets.dockerhub_password }}
          workdir: ./compose-v2/galaxy-workflow-test
          cache: true
  bioblend-test_galaxy:
    needs: [build_galaxy-server, build_galaxy-postgres, build_galaxy-htcondor, build_galaxy-configurator, build_galaxy-bioblend-test]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Set needed environment variables
        run: echo "::set-env name=IMAGE_TAG::${GITHUB_REF#refs/heads/}"
      - name: Run Bioblend tests 
        run: |
          docker-compose -f docker-compose.yml -f docker-compose.test.yml -f docker-compose.test.bioblend.yml pull
          docker-compose -f docker-compose.yml -f docker-compose.test.yml -f docker-compose.test.bioblend.yml up --exit-code-from galaxy-bioblend-test
          test_exit_code=$?
          galaxy_exit_code=$(docker inspect --format='{{.State.ExitCode}}' compose-v2_galaxy-server_1)
          [ $galaxy_exit_code -eq 1 ] && exit 1 || exit $test_exit_code
        working-directory: ./compose-v2
        continue-on-error: false
        timeout-minutes: 45
  bioblend-test_galaxy-with-restart:
    needs: [build_galaxy-server, build_galaxy-postgres, build_galaxy-htcondor, build_galaxy-configurator, build_galaxy-bioblend-test]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Set needed environment variables
        run: echo "::set-env name=IMAGE_TAG::${GITHUB_REF#refs/heads/}"
      - name: Run Bioblend tests for the first time
        run: |
          docker-compose -f docker-compose.yml -f docker-compose.test.yml -f docker-compose.test.bioblend.yml pull
          docker-compose -f docker-compose.yml -f docker-compose.test.yml -f docker-compose.test.bioblend.yml up --exit-code-from galaxy-bioblend-test
          test_exit_code=$?
          galaxy_exit_code=$(docker inspect --format='{{.State.ExitCode}}' compose-v2_galaxy-server_1)
          docker-compose -f docker-compose.yml -f docker-compose.test.yml -f docker-compose.test.bioblend.yml down
          [ $galaxy_exit_code -eq 1 ] && exit 1 || exit $test_exit_code
        working-directory: ./compose-v2
        continue-on-error: false
        timeout-minutes: 45
      - name: Clean up after first run
        run: |
          rm -rf export/postgres
          rm -rf export/galaxy/database
        working-directory: ./compose-v2
      - name: Run Bioblend tests a second time (to see if export worked as expected)
        run: |
          docker-compose -f docker-compose.yml -f docker-compose.test.yml -f docker-compose.test.bioblend.yml up --exit-code-from galaxy-bioblend-test
          test_exit_code=$?
          galaxy_exit_code=$(docker inspect --format='{{.State.ExitCode}}' compose-v2_galaxy-server_1)
          [ $galaxy_exit_code -eq 1 ] && exit 1 || exit $test_exit_code
        working-directory: ./compose-v2
        continue-on-error: false
        timeout-minutes: 45
  bioblend-test_galaxy-htcondor:
    needs: [build_galaxy-server, build_galaxy-postgres, build_galaxy-htcondor, build_galaxy-configurator, build_galaxy-bioblend-test]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Set needed environment variables
        run: echo "::set-env name=IMAGE_TAG::${GITHUB_REF#refs/heads/}"
      - name: Run Bioblend tests 
        run: |
          docker-compose -f docker-compose.yml -f docker-compose.htcondor.yml -f docker-compose.test.yml -f docker-compose.test.bioblend.yml pull
          docker-compose -f docker-compose.yml -f docker-compose.htcondor.yml -f docker-compose.test.yml -f docker-compose.test.bioblend.yml up --exit-code-from galaxy-bioblend-test
          test_exit_code=$?
          galaxy_exit_code=$(docker inspect --format='{{.State.ExitCode}}' compose-v2_galaxy-server_1)
          [ $galaxy_exit_code -eq 1 ] && exit 1 || exit $test_exit_code
        working-directory: ./compose-v2
        continue-on-error: false
        timeout-minutes: 45
  workflow-test_galaxy:
    needs: [build_galaxy-server, build_galaxy-postgres, build_galaxy-htcondor, build_galaxy-configurator, build_galaxy-bioblend-test]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Set needed environment variables
        run: echo "::set-env name=IMAGE_TAG::${GITHUB_REF#refs/heads/}"
      - name: Run Bioblend tests 
        run: |
          docker-compose -f docker-compose.yml -f docker-compose.test.yml -f docker-compose.test.workflows.yml pull
          docker-compose -f docker-compose.yml -f docker-compose.test.yml -f docker-compose.test.workflows.yml up --exit-code-from galaxy-workflow-test
          test_exit_code=$?
          galaxy_exit_code=$(docker inspect --format='{{.State.ExitCode}}' compose-v2_galaxy-server_1)
          [ $galaxy_exit_code -eq 1 ] && exit 1 || exit $test_exit_code
        working-directory: ./compose-v2
        continue-on-error: false
        timeout-minutes: 120
  workflow-test_galaxy-htcondor:
    needs: [build_galaxy-server, build_galaxy-postgres, build_galaxy-htcondor, build_galaxy-configurator, build_galaxy-bioblend-test]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Set needed environment variables
        run: echo "::set-env name=IMAGE_TAG::${GITHUB_REF#refs/heads/}"
      - name: Run Bioblend tests 
        run: |
          docker-compose -f docker-compose.yml -f docker-compose.htcondor.yml -f docker-compose.test.yml -f docker-compose.test.workflows.yml pull
          docker-compose -f docker-compose.yml -f docker-compose.htcondor.yml -f docker-compose.test.yml -f docker-compose.test.workflows.yml up --exit-code-from galaxy-workflow-test
          test_exit_code=$?
          galaxy_exit_code=$(docker inspect --format='{{.State.ExitCode}}' compose-v2_galaxy-server_1)
          [ $galaxy_exit_code -eq 1 ] && exit 1 || exit $test_exit_code
        working-directory: ./compose-v2
        continue-on-error: false
        timeout-minutes: 120