name: CI
on: [push]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Cleanup to only use compose-v2 for now
      run: rm -R compose docs galaxy  test
    - name: Run shellcheck with reviewdog
      uses: reviewdog/action-shellcheck@v1.1.3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        reporter: github-check
        level: warning
        pattern: "*.sh"
    - name: Run hadolint with reviewdog
      uses: reviewdog/action-hadolint@v1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        reporter: github-check
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Set needed environment variables
        run: echo "::set-env name=IMAGE_TAG::${GITHUB_REF#refs/heads/}"
      - name: Build Images (docker-compose.yml)
        run: docker-compose -f docker-compose.yml -f docker-compose.htcondor.yml -f docker-compose.test.yml build
        working-directory: ./compose-v2
        continue-on-error: false
      - name: Docker Login
        run: echo "${{ secrets.dockerhub_password }}" | docker login -u "${{ secrets.dockerhub_username }}" --password-stdin
      - name: Upload images to Docker Hub (docker-compose.yml)
        run: |
          docker push ${IMAGE_DOMAIN:-andreassko}/galaxy-server:${IMAGE_TAG:-latest}
          docker push ${IMAGE_DOMAIN:-andreassko}/galaxy-postgres:${IMAGE_TAG:-latest}
          docker push ${IMAGE_DOMAIN:-andreassko}/galaxy-htcondor:${IMAGE_TAG:-latest}
          docker push ${IMAGE_DOMAIN:-andreassko}/galaxy-bioblend-test:${IMAGE_TAG:-latest}
  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Set needed environment variables
        run: echo "::set-env name=IMAGE_TAG::${GITHUB_REF#refs/heads/}"
      - name: Run Bioblend tests 
        run: |
          docker-compose -f docker-compose.yml -f docker-compose.test.yml pull
          docker-compose -f docker-compose.yml -f docker-compose.test.yml up --abort-on-container-exit
          exit $(($(docker inspect --format='{{.State.ExitCode}}' compose-v2_galaxy-server_1) + $(docker inspect --format='{{.State.ExitCode}}' compose-v2_galaxy-bioblend-test_1)))
        working-directory: ./compose-v2
        continue-on-error: false